apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicename
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: servicename
    targetRevision: 
    path: 
    helm:
      valueFiles:
        
  destination:
    namespace: argocd-apps
    server: local
  syncPolicy:
    automated:
      selfHeal: true
