apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: test
    targetRevision: master
    path: values//project/test
    helm:
      valueFiles:
        
  destination:
    namespace: argocd-apps
    server: local
  syncPolicy:
    automated:
      selfHeal: true
