apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lior-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: lior-service
    targetRevision: master
    path: lior-helm-path
    helm:
      valueFiles:
        lior-helm-path
  destination:
    namespace: argocd-apps
    server: local
  syncPolicy:
    automated:
      selfHeal: true
