apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ArgoCD-Application
  title: Create a ArgoCD Application CRD
  description: BlaBla

spec:
  owner: user:yonatan.elkad
  type: kube_service
  parameters:

    - title: Choose a Source Control Management tool to store your new website in.
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

    - title: Default branch on the repository
      required:
        - defaultBranch
      properties:
        defaultBranch:
          title: Default Branch
          type: string
          description: This will be used as the default branch on the repository

    - title: Provide The service details
      required:
        - service_name
        - helm_path
        - chart_branch
        - files_path
        - owner
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        service_name:
          title: Service name
          type: string
          description: The K8s Service name.
        helm_path:
          title: Helm Chart Path
          type: string
          description: The K8s Helm Chart path.
        chart_branch:
          title: Github Branch
          type: string
          description: The branch to load the chart from
        files_path:
          title: The values files path
          type: string
          description: The path to the values files
    # - title: Helm Chart path
    #   required:
    #     - helm_path
    #   properties:
    #     helm_path:
    #       title: Helm Chart Path
    #       type: string
    #       description: The K8s Helm Chart path.

    # - title: Github Branch
    #   required:
    #     - chart_branch
    #   properties:
    #     chart_branch:
    #       title: Helm chart branch
    #       type: string
    #       description: The branch to load the chart from

    # - title: Values Files path
    #   required:
    #     - files_path
    #   properties:
    #     files_path:
    #       title: The values files path
    #       type: string
    #       description: The path to the values files

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          service_name: ${{ parameters.service_name }}
          chart_branch: ${{ parameters.chart_branch }}
          helm_path: ${{ parameters.helm_path }}
          files_path: ${{ parameters.helm_path }}

    - id: publishToGitHub
      name: Publish to GitHub
      action: publish:github:pull-request
      input:
        repoUrl: 'github.com?repo=${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}&owner=${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}'
        #repoUrl: 'github.com?repo=reponame&owner=owner'
        branchName: ${{ parameters.defaultBranch }}
        description: 'A static HTML website. Just like the good old days.'
        title: Add-service ${{ parameters.service_name }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publishToGitHub.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info2.yaml'
  output:
    remoteUrl: ${{ steps.publishToGitHub.output.remoteUrl }}
