apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.service_name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${{ values.service_name }}
    targetRevision: ${{ values.service_branch }}
    path: ${{ values.service_helm_path }}
    helm:
      valueFiles:
        ${{ values.values_files_path }}
  destination:
    namespace: argocd-apps
    server: local
  syncPolicy:
    automated:
      selfHeal: true
